### ISSUE TITLE
Goowls 1080P IP Camera supported!

### ISSUE THREAD

**Issue by iMilnb** [cjj25/Yi-RTS3903N-RTSPServer#21]
Just pointing out that this camera https://www.newegg.com/p/2P0-02K4-00008 has exactly the same firmware as the Cacagoo XY-R9420-X2 (7.1.00.25A_202002271051) and thus the archive works out of the box.
Firmware backup is here: https://imil.net/stuff/goowls_dump.tgz

**Comment by cjj25** [comment]
Thanks for the update and firmware :-)
Similar devices here: https://github.com/cjj25/Yi-RTS3903N-RTSPServer/issues/5#issuecomment-903747367

**Comment by Timmy-Harris** [comment]
@iMilnb Hello! Could you please share firmware backup? 'cause this link https://imil.net/stuff/goowls_dump.tgz does not work :(
Is there any way to update a very similar camera based on MVT9632-SC2303_V1.0 with your backup? 
Thank you in advance.

**Comment by Timmy-Harris** [comment]
The vendor is Sdeter A8. I'm using V380 application.
![photo_2022-07-05_15-37-41](https://user-images.githubusercontent.com/108498462/177329286-eae433e7-2bb3-4288-bd9b-6df3da830ce4.jpg)

**Comment by cjj25** [comment]
When you use the payload from this repository on your SD card, does it do a firmware dump  (create a backup folder on the root of the SD card)?

**Comment by Timmy-Harris** [comment]
Unfortunately, it does nothing. The device just started video recording and saved it into RecFiles folder.

**Comment by cjj25** [comment]
I'd love to have a firmware dump to see if there is a payload we could create for other users. 

Do you have access to UART? 

[UART information here.](https://github.com/TheCrypt0/yi-hack-v4/issues/154#issuecomment-1038244399)

**Comment by cjj25** [comment]
https://github.com/TheCrypt0/yi-hack-v4/issues/154#issuecomment-903343524

**Comment by Timmy-Harris** [comment]
Yes, I have UART converter. I'll try to connect this board.

**Comment by Timmy-Harris** [comment]
I've got the same behavior as [bondiblueos9](https://github.com/bondiblueos9) got. I wired up those pads but got nothing. I tried the tx and rx both ways. Checked two middle pins and those pins connected to the RTS3903N chip.

**Comment by Ammarpic** [comment]
> Just pointing out that this camera https://www.newegg.com/p/2P0-02K4-00008 has exactly the same firmware as the Cacagoo XY-R9420-X2 (7.1.00.25A_202002271051) and thus the archive works out of the box.
I have a problem with the camera
I need the basic software
Please help
