### ISSUE TITLE
Change username and password

### ISSUE THREAD

**Issue by Juanjod54** [cjj25/Yi-RTS3903N-RTSPServer#23]
Hi!
i've tried the rtsp server, it looks great on a Mibao D600 camera. I'm trying to configure the camera to be more secure, so, I was wondering if there is any way to change the username, password and even the port where the cam is streaming to.

Thanks in advance!

Regards

**Comment by cjj25** [comment]
Thanks for feedback, I'm pleased it's working for you! Could you provide a firmware dump of your camera? Not seen that one before.

For changing the telnet passwords, you could mount bind the /etc/ directory. [A user has made a pull request](https://github.com/cjj25/Yi-RTS3903N-RTSPServer/pull/20), I've not fully tested it yet. 

As for securing the RTSP stream, I've not implemented anything for this as I use my IP cameras on separate VLANs here.
