### ISSUE TITLE
Yi-IoT camera

### ISSUE THREAD

**Issue by OvCa77** [cjj25/Yi-RTS3903N-RTSPServer#25]
I am just wanting to share that your project also works on Yi-IoT camera (no model found on case) and sharing backup if someone wants to further develop
Firmware: 7.0.00.90A_201904301632
[backup_yiiot.zip](https://github.com/cjj25/Yi-RTS3903N-RTSPServer/files/8863888/backup_yiiot.zip)
.

**Comment by cjj25** [comment]
Thanks @OvCa77
