### ISSUE TITLE
WORKS FOR YI IOT OUTDOOR CAMERA MODEL XY-R9520-V3

### ISSUE THREAD

**Issue by Abuelika** [cjj25/Yi-RTS3903N-RTSPServer#4]
Thanks! I have tried the steps and it works for this camera model.

**Comment by cjj25** [comment]
Thank you for the feedback!

**Comment by cjj25** [comment]
For reference it appears your camera shares the same board as many models:

Model No.: XY/TA-R9820-F12, XY/TA-R9820-F11, XY/TA-R9820-F13, XY/TA-R9820-
F14, XY/TA-R9820-K7, XY/TA-R9820-K8, XY/TA-R9820-K9, XY/TA-R9820-K10, 
XY/TA-R9820-Q11, IPC-A3610-A111, IPC/TA-A3610-XHR, XY/TA-R9520-V8, XY/TA-
R9520-V9, IPC-R9520-V7, TA-A3410-R6, IPC-C3310-R7 , XY-W102R, TA-FD-BL6, 
TA-FD-BL7, TA-R9522-AFD 

FCC ID: 2APD7-XYTAR9820F12
https://fccid.io/2APD7-XYTAR9820F12/Internal-Photos/09-77622-IntPho-4381529
